modLoader="javafml"
loaderVersion="[36,)"
license="Apache-2.0"

[[mods]]
modId="shieldexp"
version="${file.jarVersion}"
displayName="Shield Expansion"
authors="Infernal Studios"
description='''
Shield Expansion is a mod that aims to make combat in Minecraft more engaging and skillful by rebalancing shields. The mod adds traditional tiers to shields and introduces two new mechanics, Universal Cooldown and Parrying, in addition to adding fun enchantments and cool customization options!
Universal Cooldown means any attack that hits a shield will put it into a state of cooldown for 1 second, forcing you to either go on the offensive or make better use of defensive manoeuvring. You also go into this 1 second cooldown if you lower the shield, too.
Parrying an attack, done by raising your shield just before an attack hits you, allows you to bypass Universal Cooldown, rewarding skillful timing and use of your shield. You also push any melee attackers back upon a successful Parry, too.
We hope you enjoy it!
Credits
Kuraion - Developer
HellionGames, CaelTheQuail, LudoCrypt - Developer
Nekomaster1000 - Conceptualiser, Artist
EB Mario - Concept Collaborator
Kasualix - 1.16.5 Forge Porter
'''
